name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-package:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
    
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '24'
    
    # Build the CLI solution and publish the CLI binaries for both x64 and ARM64 architectures
    - name: Build CLI solution
      run: dotnet build src\winsdk-CLI\winsdk.sln -c Release
    # Todo: Add tests
    - name: Publish CLI for x64
      run: dotnet publish src\winsdk-CLI\Winsdk.Cli\Winsdk.Cli.csproj -c Release -r win-x64 --self-contained
    - name: Publish CLI for ARM64
      run: dotnet publish src\winsdk-CLI\Winsdk.Cli\Winsdk.Cli.csproj -c Release -r win-arm64 --self-contained
    - name: Upload CLI binaries
      uses: actions/upload-artifact@v4
      with:
        name: cli-binaries
        path: |
          src/winsdk-CLI/Winsdk.Cli/bin/Release/net9.0/win-x64/publish/
          src/winsdk-CLI/Winsdk.Cli/bin/Release/net9.0/win-arm64/publish/

    # Build npm package and upload the package and tarball as artifacts
    - name: Build complete npm package (copy binaries only)
      run: |
        cd src\winsdk-npm
        npm run build-copy-only
    - name: Create npm package
      run: |
        cd src\winsdk-npm
        npm pack
    - name: Upload npm package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: npm-package
        path: |
          src/winsdk-npm/**
          !src/winsdk-npm/bin/**/*.pdb
          !src/winsdk-npm/node_modules/**
          !src/winsdk-npm/*.tgz
    - name: Upload npm tarball
      uses: actions/upload-artifact@v4
      with:
        name: npm-tarball
        path: src\winsdk-npm\*.tgz
